services:
  - type: web
    name: barberia-ghs-api
    runtime: docker
    plan: free
    region: virginia
    branch: feature/production-readiness-billing
    autoDeployTrigger: 'off'
    healthCheckPath: /actuator/health/readiness
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: BILLING_MANUAL_INSTRUCTIONS
        sync: false
      - key: WOMPI_ENABLED
        value: 'false'
